import { Inter } from 'next/font/google'
import '../globals.css'
import Sidebar from '@/components/shared/Sidebar'
import Topbar from '@/components/shared/Topbar'
import Footer from '@/components/shared/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=' flex  overflow-x-hidden'>

        <Sidebar />
        <Topbar />
        <main className="ml-[257px]  relative w-full px-8">
          <section className="w-full">
            <div className="w-full">{children}</div>
          </section>
        </main>
        </div>
        <Footer/>
      </body>
    </html>
  )
}
